language: generic

sudo: required

services:
    - docker

env:
    global:
        - secure: mfDuMHTAW8y1ssTbf7wihtOrJ5qosBbwri5PX9m09M5TEgTy2hW38x5EOoeQHqILrkvbunz3uOok7hXaeoZvw8uAW4XQZTBHWyEovBW1XuqJopUtM8tzPI2XpVttBPALVZZOGFLZ4ZXxKkCXSLwamkt+cYhJyoew6/rMfFpViyBFC3trYZChVtqcLU7lKOlDcp4RTKTd/wJ1CThSx/SZo0aPO17o8gjFK1GI2TnJjZODUm0rJBoGAK2398wjLyVkYYAS3hM+SZ3AH4rHIqsX5k1UHggDGv2khcddsQ1FCI/Lfx5HUkANd6j5XFOnizfX6ozsWHyKZQBtgJwhxjgGdRerDxe9arNRXIijjgsMdT58gvLarRTo+aV4AWVr10vp45GQYGYMMhJz5jZfXnbzCEfVLhJBOzIeWsFn9Cy+5AKMOElt0nV1ZnKTfn3nOqlW+4DM9SBAMhSbYyRabvDJMCGKRa+uPP4VEpXpFWbLZkIwHt+KEiKQX2kcgrSeIHkN9rmhplAb/W1ctJjHhwp0EHNWxmz+t1nbiiAzpKPPwIxw6q6nMAXJdKbQjDPvP6mdd+xCjsrf+ay9BXxGmh2aYmS+WmLXLoXd0RuhZlBME03NaCtGU08kKNVEPTrOv7hMZuf6QEvzgrJp/t0+4pqC0cpBX76Smbt39qgfxvVXxfU=
        - secure: YaGKLiRhx/qCTadfkILoKRcOrfxwysGcb5CDFZ9/6AiW7Z/5msvzJnQkKRy8GZ1UaWNJcrOG9cpZ/WQlNezF0F2XqLcHWMsUBZeuZyvUshJCyoSgxnA3kTUL/tEKVPXQft4REUa1/BXJRMz0/01VRnVzaVd+Hx6rAJ0qc1tkm0HYzZGiWLGj2DcpO1cP0KGk+XqPAROTLHCZYeppOY8mMVlK3XG5wSzJyWPVpKF57us6Bewmfaa8kWEWSbqwgPj+Sm26Ho+DZSnHEkp6yIDddtYBk7M65GRZuzN7ofUaH3SLDreMjxZeXxS3HNgz5T3NdrAPGGIfBWF4XhySYklYSl5gp0eD7X754Y9TX7pQqGg9n7Zb9XevEgSQUUf0R166H9wrYHrmQtZX9+HDamEIieAbWMznZ98gToVqfSeAkB8dezT3Wdr7pAmJVpRdQP99UgKBOhVy0z+DuhMxxpY8AbNpS9mo0LemcjXLKP27DrpqGzwT1ux+gdbkGlkY4ILzFLROOuU2RUk6kDCUQBFnu3yRghSHM8VexBKskXaYMxXa9qED9W17jYgFJpreQ6tEmrnTdJrApbzLVKsKaczP7m4qqZocTgnX03wUnk5Hwv9lOJ7+D3QXCiwvMxYfv6Xj30YfnP8vypO0YPkK1HVEv66igdmGg9ZV+vk3q9couyU=

before_script:
    - docker pull alpine:3.4

script:
    - make

after_success:
    - docker images
